spring.application.name=moTI
spring.datasource.url=jdbc:postgresql://localhost:5432/moti_db
spring.datasource.username=postgres
spring.datasource.password=biju0507
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080